### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by deavmi** [MaxNetMesh/maxnetmesh.github.io#5]
- [x] Remove tracking code
- [x] Remove notice from site
- [x] Remove notice from README

**Comment by Walkman100** [comment]
Why did you even have google analytics? I don't have google analytics on any of my pages, not even my (old) blog.

**Comment by deavmi** [comment]
@Walkman100 I do like tracking. But removed it knowing it is morally wrong. Actually fuck tracking I do hate it. It is depriving rights of the user. Well already in my apps I do not have it. I would never add it. It is an ugly feature to have.
